### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by zippynk** [JacobEdelman/lark#3]
This makes doing virtually anything with lark illegal.

**Comment by JacobEdelman** [comment]
Ah, I couldn't decide on one initially and decided to wait. Now would definitely be a good time to add one. Recommendations? I'd prefer a stronger one that I would have the option of changing later.

**Comment by zippynk** [comment]
I recommend the Mozilla Public License - it allows people to write programs under any license in lark, and link it to any code, but keeps the code of lark itself under open source licenses. If you're more of the GPL-based license type, then the LGPL does a similar thing (although it doesn't allow certain types of linking, but that shouldn't be an issue, since it's Python and there's no static/dynamic linking).

**Comment by zippynk** [comment]
Also, if you want, you can add an "Incompatible with Secondary Licenses" notice to the MPL, which disallows converting the code to other open source licenses (such as the (L/A)GPL), if you care about that.

**Comment by JacobEdelman** [comment]
I'd prefer to ensure that for-profit companies need permission from me before using it.

**Comment by zippynk** [comment]
Ah - I'd advise against that.
if you do that, it won't count as Open Source or Free Software - the FSF and the OSI have made it clear that both terms imply allowing commercial use. Since people look for packages under licenses defined as open source and free, even if you don't care about it (I don't particularly), it's still a big disadvantage to have one that is rejected, especially by both organizations.
However, you can pick a license that requires your code to remain open source. The MPL and LGPL do this somewhat - the GPL fully enforces it for all linked code, but I wouldn't recommend using that.
